name: 📚 Documentation
description: 문서 추가 또는 수정
title: "📚 DOC: "
labels: ["Docs"]
body:
  - type: input
    id: summary
    attributes:
      label: 변경 내용
      placeholder: 어떤 문서를 수정/추가했나요?
  - type: textarea
    id: reason
    attributes:
      label: 이유
      placeholder: 이 문서를 수정하거나 추가한 이유는?
