name: ✨ Feature
description: A minimal feature request.
body:
  - type: textarea
    id: feature-request
    attributes:
      label: What is the feature you would like to see?
    validations:
      required: true
