name: ✨ Feature
description: 새로운 기능을 개발할 때 사용
title: "✨ FEAT: "
labels: ["Feat"]
body:
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      placeholder: 어떤 기능을 구현하나요?
  - type: textarea
    id: details
    attributes:
      label: 기능 설명
      placeholder: 해당 기능의 작동 방식, UI 변화 등
  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 기능 정의 완료
        - label: UI/UX 고려됨
        - label: 테스트 계획 있음
