name: 🚨 Fix
description: 버그 수정
title: "🚨 Fix: "
labels: ["Fix"]
body:
  - type: input
    id: branch
    attributes:
      label: 브랜치 이름
      description: 작업할 브랜치 이름을 명확하게 작성해주세요 (예: Fix/#-)
      placeholder: 예: Fix/#-
    validations:
      required: true
  - type: input
    id: summary
    attributes:
      label: 간단 요약
  - type: textarea
    id: details
    attributes:
      label: 수정한 버그의 상세 설명
  - type: input
    id: related
    attributes:
      label: 관련 이슈
      placeholder: 예) #42
