name: 🚨 Fix
description: 버그를 수정할 때 사용
title: "🚨 FIX: "
labels: ["Fix"]
body:
  - type: input
    id: summary
    attributes:
      label: 버그 요약
      placeholder: 어떤 문제가 발생했나요?
  - type: textarea
    id: steps
    attributes:
      label: 버그 재현 절차
      description: 버그를 재현하는 방법
      placeholder: 1. 앱 실행 → 2. 버튼 클릭 → 3. 에러 발생
  - type: textarea
    id: solution
    attributes:
      label: 해결 방법
      placeholder: 어떻게 해결했는지 설명해 주세요
