name: 🚀 Perf
description: 성능 개선
title: "🚀 Perf: "
labels: ["Perf"]
body:
  - type: input
    id: branch
    attributes:
      label: 브랜치 이름
      description: 작업할 브랜치 이름을 명확하게 작성해주세요 예) Perf/#-
      placeholder: 예) Perf/#-
    validations:
      required: true
  - type: input
    id: summary
  - type: textarea
    id: details
