name: 🔨 Refactor
description: 기능 변경 없이 코드 리팩토링
title: "🔨 Refactor: "
labels: ["Refactor"]
body:
  - type: input
    id: branch
    attributes:
      label: 브랜치 이름
      description: 작업할 브랜치 이름을 명확하게 작성해주세요 예) Refactor/#-
      placeholder: 예) Refactor/#-
    validations:
      required: true
  - type: input
    id: summary
  - type: textarea
    id: details
