name: 🎨 Style
description: 코드 포맷, 네이밍, 스타일 변경
title: "🎨 Style: "
labels: ["Style"]
body:
  - type: input
    id: branch
    attributes:
      label: 🔀 브랜치 이름
      description: 작업할 브랜치 이름을 명확하게 작성해주세요 (예: Style/#-)
      placeholder: 예: Style/#-
    validations:
      required: true
  - type: input
    id: summary
  - type: textarea
    id: details
  - type: input
    id: related
    attributes:
      label: 관련 이슈
      placeholder: 예) #42
